// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Follow struct {
	InitiatorID uuid.UUID
	TargetID    uuid.UUID
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Post struct {
	ID         uuid.UUID
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	IsDeleted  bool
	Visibility string
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UserPreference struct {
	ID          uuid.UUID
	AvatarUrl   string
	CoverUrl    string
	DarkMode    bool
	PrivateMode bool
	UserID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
