// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_preferences.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
INSERT INTO user_preferences (id, user_id)
VALUES (gen_random_uuid(), $1)
`

func (q *Queries) CreateUserPreferences(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createUserPreferences, userID)
	return err
}
