// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const changeAvatarForuser = `-- name: ChangeAvatarForuser :exec
UPDATE user_preferences SET avatar_url = $1 WHERE user_id = $2
`

type ChangeAvatarForuserParams struct {
	AvatarUrl string
	UserID    uuid.UUID
}

func (q *Queries) ChangeAvatarForuser(ctx context.Context, arg ChangeAvatarForuserParams) error {
	_, err := q.db.ExecContext(ctx, changeAvatarForuser, arg.AvatarUrl, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, hashed_password, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, username, email, hashed_password, created_at, updated_at
`

type CreateUserParams struct {
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getNonFriendUsers = `-- name: GetNonFriendUsers :many
SELECT
    u.id as user_id,
    u.username,
    u.email,
    u.hashed_password,
    u.created_at as user_created_at,
    u.updated_at as user_updated_at,
    up.avatar_url
FROM
    users u
LEFT JOIN
    user_preferences up ON up.user_id = u.id
WHERE u.id != $1
AND NOT EXISTS (
    SELECT 1 FROM friends f 
    WHERE (f.user_id = $1 AND f.friend_id = u.id)
    OR (f.friend_id = $1 AND f.user_id = u.id)
)
`

type GetNonFriendUsersRow struct {
	UserID         uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	UserCreatedAt  time.Time
	UserUpdatedAt  time.Time
	AvatarUrl      sql.NullString
}

func (q *Queries) GetNonFriendUsers(ctx context.Context, id uuid.UUID) ([]GetNonFriendUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNonFriendUsers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNonFriendUsersRow
	for rows.Next() {
		var i GetNonFriendUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, hashed_password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT 
    u.id as user_id,
    u.username,
    u.email,
    u.hashed_password,
    u.created_at as user_created_at,
    u.updated_at as user_updated_at,
    up.id as preferences_id,
    up.avatar_url,
    up.cover_url,
    up.dark_mode,
    up.created_at as preferences_created_at,
    up.updated_at as preferences_updated_at
FROM 
    users u
LEFT JOIN
    user_preferences up ON up.user_id = u.id
WHERE u.id = $1
`

type GetUserByIdRow struct {
	UserID               uuid.UUID
	Username             string
	Email                string
	HashedPassword       string
	UserCreatedAt        time.Time
	UserUpdatedAt        time.Time
	PreferencesID        uuid.NullUUID
	AvatarUrl            sql.NullString
	CoverUrl             sql.NullString
	DarkMode             sql.NullBool
	PreferencesCreatedAt sql.NullTime
	PreferencesUpdatedAt sql.NullTime
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.PreferencesID,
		&i.AvatarUrl,
		&i.CoverUrl,
		&i.DarkMode,
		&i.PreferencesCreatedAt,
		&i.PreferencesUpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    u.id as user_id,
    u.username,
    u.email,
    u.hashed_password,
    u.created_at as user_created_at,
    u.updated_at as user_updated_at,
    up.id as preferences_id,
    up.avatar_url,
    up.cover_url,
    up.dark_mode,
    up.created_at as preferences_created_at,
    up.updated_at as preferences_updated_at
FROM 
    users u
LEFT JOIN
    user_preferences up ON up.user_id = u.id
WHERE u.username = $1
`

type GetUserByUsernameRow struct {
	UserID               uuid.UUID
	Username             string
	Email                string
	HashedPassword       string
	UserCreatedAt        time.Time
	UserUpdatedAt        time.Time
	PreferencesID        uuid.NullUUID
	AvatarUrl            sql.NullString
	CoverUrl             sql.NullString
	DarkMode             sql.NullBool
	PreferencesCreatedAt sql.NullTime
	PreferencesUpdatedAt sql.NullTime
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.PreferencesID,
		&i.AvatarUrl,
		&i.CoverUrl,
		&i.DarkMode,
		&i.PreferencesCreatedAt,
		&i.PreferencesUpdatedAt,
	)
	return i, err
}

const resetUsersTable = `-- name: ResetUsersTable :exec
delete from users
`

func (q *Queries) ResetUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsersTable)
	return err
}
