-- -- name: CreateFriend :exec
-- INSERT INTO friends (user_id, friend_id, initiator_id)
-- values ($1, $2, $3);
--
-- -- name: GetAllPendingRequests :many
-- SELECT * FROM friends WHERE status = 'pending';
--
-- -- name: GetFriendsList :many
-- SELECT 
--     f.*,
--     u.username as friend_username,
--     up.avatar_url as friend_avatar_url
--     -- future fields
-- FROM 
--     friends f
-- JOIN 
--     users u ON (
--         CASE 
--             WHEN f.user_id = $1 THEN f.friend_id
--             ELSE f.user_id
--         END = u.id
--     )
-- LEFT JOIN
--     user_preferences up ON up.user_id = u.id
-- WHERE 
--     f.status = 'accepted' AND (f.user_id = $1 OR f.friend_id = $1);
--
-- -- name: GetFriendRequests :many
-- SELECT 
--     f.*,
--     u.username as friend_username,
--     up.avatar_url as friend_avatar_url
--     -- future fields
-- FROM 
--     friends f
-- JOIN 
--     users u ON (
--         CASE 
--             WHEN f.user_id = $1 THEN f.friend_id
--             ELSE f.user_id
--         END = u.id
--     )
-- LEFT JOIN
--     user_preferences up ON up.user_id = u.id
-- WHERE 
--     f.status = 'pending' AND (f.user_id = $1 OR f.friend_id = $1) AND initiator_id != $1;
--
-- -- name: UpdateFriendStatus :exec
-- UPDATE friends SET status = $1 WHERE user_id = $2 AND friend_id = $3;
--
-- -- name: DeleteFriend :exec
-- DELETE FROM friends WHERE user_id = $1 AND friend_id = $2;
--
-- -- name: ResetFriendsTable :exec
-- DELETE FROM friends;
